settings:
  app_name: "DataMask ETL"
  batch_size: 1000
  extraction_window_days: 90 

databases:
  source_db_env_var: "SUPABASE_PROD_URI"
  target_db_env_var: "SUPABASE_QA_URI"

tables:
  - name: "clientes"
    pk: "id"
    filter_column: "fecha_registro"
    masking_rules:
      nombre: "fake_name"
      email: "hash_email"
      telefono: "preserve_format"
      direccion: "redact"

  - name: "ordenes"
    pk: "id"
    filter_column: "fecha"        
    masking_rules:
      total: "none"

  - name: "detalle_ordenes"
    pk: "id"
    masking_rules:
      producto: "redact"     
      precio_unitario: "none"